point1: /eos/user/m/mschrode/mcproduction/gridpacks/Run3/GF_HHH/GF_HHH_c3_0_d4_0_el8_amd64_gcc10_CMSSW_12_4_8_tarball.tar.xz
point2: /eos/user/m/mschrode/mcproduction/gridpacks/Run3/GF_HHH/GF_HHH_c3_0_d4_0_el8_amd64_gcc10_CMSSW_12_4_8_tarball.tar.xz
